table 'Dimension BARCO'
	lineageTag: ad370d54-4ddb-4e6d-aa1e-63896a4c27fb

	column COD_BARCO
		dataType: int64
		formatString: 0
		lineageTag: 29a7d4dd-aff1-4645-bd65-0b4a355fa587
		summarizeBy: none
		sourceColumn: COD_BARCO

		annotation SummarizationSetBy = Automatic

	column NOMBRE_BARCO
		dataType: string
		lineageTag: 2c1b86bc-809b-4b59-9d5d-a4b2f0092c8d
		summarizeBy: none
		sourceColumn: NOMBRE_BARCO

		annotation SummarizationSetBy = Automatic

	partition 'Dimension BARCO' = m
		mode: import
		source =
				let
				    Source = Sql.Databases("192.168.169.110"),
				    Analytics = Source{[Name="Analytics"]}[Data],
				    Dimension_BARCO = Analytics{[Schema="Dimension",Item="BARCO"]}[Data],
				    #"Filas filtradas" = Table.SelectRows(Dimension_BARCO, each [NOMBRE_BARCO] <> null and [NOMBRE_BARCO] <> ""),
				    #"Duplicados quitados" = Table.Distinct(#"Filas filtradas", {"COD_BARCO"}),
				    #"Personalizada agregada" = Table.AddColumn(#"Duplicados quitados", "NOMBRE_BARCO.1", each Text.Combine(
				    List.Transform(
				        Text.Split([NOMBRE_BARCO], " "),
				        (palabra) =>
				            if List.Contains(
				                {"I","II","III","IV","V","VI","VII","VIII","IX","X"},
				                palabra
				            )
				            then palabra
				            else Text.Proper(Text.Lower(palabra))
				    ),
				    " "
				)),
				    #"Columnas quitadas" = Table.RemoveColumns(#"Personalizada agregada",{"NOMBRE_BARCO"}),
				    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Columnas quitadas",{{"NOMBRE_BARCO.1", "NOMBRE_BARCO"}})
				in
				    #"Columnas con nombre cambiado"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación

