table 'Dimension FLOTA'
	lineageTag: 6c136d7f-95e0-4817-a4e6-d59bcaf8a1df

	column CODIGO_FLOTA
		dataType: int64
		formatString: 0
		lineageTag: 7771b60d-5823-496c-8991-423075a734eb
		summarizeBy: none
		sourceColumn: CODIGO_FLOTA

		annotation SummarizationSetBy = Automatic

	column TIPO_FLOTA
		dataType: string
		lineageTag: c0ed6165-42c9-4cf4-b297-29d401e55870
		summarizeBy: none
		sourceColumn: TIPO_FLOTA

		annotation SummarizationSetBy = Automatic

	partition 'Dimension FLOTA' = m
		mode: import
		source =
				let
				    Source = Sql.Databases("192.168.169.110"),
				    Analytics = Source{[Name="Analytics"]}[Data],
				    Dimension_FLOTA = Analytics{[Schema="Dimension",Item="FLOTA"]}[Data],
				    #"Poner En Mayúsculas Cada Palabra" = Table.TransformColumns(Dimension_FLOTA,{{"TIPO_FLOTA", Text.Proper, type text}})
				in
				    #"Poner En Mayúsculas Cada Palabra"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación

