// Le damos la bienvenida a la vista de consultas DAX. Obtenga más información sobre las consultas DAX en https://aka.ms/dax-queries.
// Haga clic con el botón derecho en tablas, columnas o medidas en el panel de datos para acceder a consultas rápidas o pida ayuda a Copilot para escribir DAX.

// Seleccione "Ejecutar" para probar esta consulta DAX de ejemplo.
EVALUATE
CALCULATETABLE(
    SUMMARIZE(
        FILTER(
            PB_VIAJE_MUESTREO,

                 PB_VIAJE_MUESTREO[PROYECTO] = "PN" 
				&& RELATED('Date'[Year]) = 2008
				&& PB_VIAJE_MUESTREO[CODIGO_FLOTA] = 2
				&& PB_VIAJE_MUESTREO[CODIGO_REGION] = 15
				
        ),
        PB_VIAJE_MUESTREO[COD_BARCO],
        PB_VIAJE_MUESTREO[FECHA]
    )
)

