table 'Dimension PUERTO'
	lineageTag: f4cbe46c-71af-4202-94ea-f25437547ef1

	column CODIGO_PUERTO
		dataType: int64
		formatString: 0
		lineageTag: 89704f70-6ebb-4aee-91b9-29c22c660e4b
		summarizeBy: none
		sourceColumn: CODIGO_PUERTO

		annotation SummarizationSetBy = Automatic

	column PUERTO
		dataType: string
		lineageTag: ccd9c51d-5acb-4c64-b6bd-04fc32033f65
		summarizeBy: none
		sourceColumn: PUERTO

		annotation SummarizationSetBy = Automatic

	partition 'Dimension PUERTO' = m
		mode: import
		source =
				let
				    Source = Sql.Databases("192.168.169.110"),
				    Analytics = Source{[Name="Analytics"]}[Data],
				    Dimension_PUERTO = Analytics{[Schema="Dimension",Item="PUERTO"]}[Data],
				    #"Duplicados quitados" = Table.Distinct(Dimension_PUERTO, {"CODIGO_PUERTO"}),
				    #"Quitar COD_PUERTO nulo" = Table.SelectRows(#"Duplicados quitados", each ([CODIGO_PUERTO] <> null))
				in
				    #"Quitar COD_PUERTO nulo"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación

