table 'Dimension MAESTRO ESPECIE'
	lineageTag: eb91ca5a-7ae2-45e4-a1fb-ddc9ff56ffa2

	column COD_ESPECIE
		dataType: int64
		formatString: 0
		lineageTag: e9a398f2-6e59-495f-a5ce-671eb80740c5
		summarizeBy: none
		sourceColumn: COD_ESPECIE

		annotation SummarizationSetBy = Automatic

	column NOMBRE_ESPECIE
		dataType: string
		lineageTag: b242ad52-084c-44e4-ab78-bac3fecd774d
		summarizeBy: none
		sourceColumn: NOMBRE_ESPECIE

		annotation SummarizationSetBy = Automatic

	partition 'Dimension MAESTRO ESPECIE' = m
		mode: import
		source =
				let
				    Origen = Sql.Database("192.168.169.110", "Analytics"),
				    Dimension_PB_MAESTRO_ESPECIE = Origen{[Schema="Dimension",Item="PB_MAESTRO_ESPECIE"]}[Data],
				    #"Poner En Mayúsculas Cada Palabra" = Table.TransformColumns(Dimension_PB_MAESTRO_ESPECIE,{{"NOMBRE_ESPECIE", Text.Proper, type text}})
				in
				    #"Poner En Mayúsculas Cada Palabra"

	annotation PBI_ResultType = Exception

	annotation PBI_NavigationStepName = Navegación

