table PB_REQ_VIAJES
	lineageTag: 701cf170-12da-43f6-988b-4053ccdfc70f

	column ID
		dataType: int64
		formatString: 0
		lineageTag: 6652a5ba-c025-4204-a0d4-157246aafd17
		summarizeBy: count
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	column COD_PROYECTO
		dataType: string
		lineageTag: 4654a202-9f30-4b83-ac22-4b1896b062b4
		summarizeBy: none
		sourceColumn: COD_PROYECTO

		annotation SummarizationSetBy = Automatic

	column MES
		dataType: int64
		formatString: 0
		lineageTag: 7a909be7-41e9-4296-bdc6-012e647b75d5
		summarizeBy: sum
		sourceColumn: MES

		annotation SummarizationSetBy = Automatic

	column PERIODO
		dataType: int64
		formatString: 0
		lineageTag: 20ffa8f0-a7c3-4465-ba63-bb267d43e60f
		summarizeBy: sum
		sourceColumn: PERIODO

		annotation SummarizationSetBy = Automatic

	column TOT_VIAJE_EMB
		dataType: int64
		formatString: 0
		lineageTag: 5179f585-5094-452a-b90a-778795fb3f0d
		summarizeBy: sum
		sourceColumn: TOT_VIAJE_EMB

		annotation SummarizationSetBy = Automatic

	column TOT_LANCE_EMB
		dataType: int64
		formatString: 0
		lineageTag: 0eceb4ab-66be-457c-86c9-5e85ac1bc5f0
		summarizeBy: sum
		sourceColumn: TOT_LANCE_EMB

		annotation SummarizationSetBy = Automatic

	column TOT_VIAJE_ENC
		dataType: int64
		formatString: 0
		lineageTag: e003e57d-8593-488a-a3fb-094df8e27aa5
		summarizeBy: sum
		sourceColumn: TOT_VIAJE_ENC

		annotation SummarizationSetBy = Automatic

	column TOT_VIAJE_MEST
		dataType: int64
		formatString: 0
		lineageTag: 8c75da11-55b0-4f7b-b503-2502385789f4
		summarizeBy: sum
		sourceColumn: TOT_VIAJE_MEST

		annotation SummarizationSetBy = Automatic

	column COD_REGION
		dataType: int64
		formatString: 0
		lineageTag: 589bba80-f202-4173-9bf0-c57563704916
		summarizeBy: none
		sourceColumn: COD_REGION

		annotation SummarizationSetBy = Automatic

	column CENTRO_OP
		dataType: string
		lineageTag: cd6e4746-0f8a-481a-9015-d4e2b31d3d09
		summarizeBy: none
		sourceColumn: CENTRO_OP

		annotation SummarizationSetBy = Automatic

	column PESQUERIA
		dataType: string
		lineageTag: 0cc1a906-7ab9-43f9-8fc0-a9ee1c9fc0fc
		summarizeBy: none
		sourceColumn: PESQUERIA

		annotation SummarizationSetBy = Automatic

	column PERIODOMES = FORMAT(PB_REQ_VIAJES[PERIODO], "0000") & "-" & FORMAT(PB_REQ_VIAJES[MES], "00")
		lineageTag: bafd6556-07f5-4022-87f0-87965e1d3e5c
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column COD_FLOTA
		dataType: int64
		formatString: 0
		lineageTag: 16256aa1-7151-426c-a52f-18374932e4d0
		summarizeBy: none
		sourceColumn: COD_FLOTA

		annotation SummarizationSetBy = Automatic

	column COD_PUERTO
		dataType: int64
		formatString: 0
		lineageTag: c1a2003f-43f3-4acd-a06c-1b71139e3792
		summarizeBy: none
		sourceColumn: COD_PUERTO

		annotation SummarizationSetBy = Automatic

	column FLOTA
		dataType: string
		lineageTag: 95a4107b-cb01-4d27-b04b-a1a7f0ddd48e
		summarizeBy: none
		sourceColumn: FLOTA

		annotation SummarizationSetBy = Automatic

	column PUERTO
		dataType: string
		lineageTag: 6dd4213b-c860-42bc-9cbc-231031a8c6c2
		summarizeBy: none
		sourceColumn: PUERTO

		annotation SummarizationSetBy = Automatic

	partition PB_REQ_VIAJES = m
		mode: import
		source =
				let
				    Source = Sql.Databases("192.168.169.110"),
				    Analytics = Source{[Name="Analytics"]}[Data],
				    Fact_PB_REQ_VIAJES = Analytics{[Schema="Staging",Item="PB_REQ_VIAJES"]}[Data],
				    #"Texto limpio" = Table.TransformColumns(Fact_PB_REQ_VIAJES,{{"COD_PROYECTO", Text.Clean, type text}}),
				    #"Valor reemplazado" = Table.ReplaceValue(#"Texto limpio","Descarte","DES",Replacer.ReplaceText,{"COD_PROYECTO"}),
				    #"Valor reemplazado1" = Table.ReplaceValue(#"Valor reemplazado","DES_cerco","DES_CER",Replacer.ReplaceText,{"COD_PROYECTO"}),
				    #"Filas filtradas" = Table.SelectRows(#"Valor reemplazado1", each true)
				in
				    #"Filas filtradas"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación

