table PB_VIAJE_MUESTREO_TEST
	lineageTag: 190195d3-3388-4bce-9613-a563e60a52f9

	column mes = MONTH(PB_VIAJE_MUESTREO_TEST[FECHA])
		formatString: 0
		lineageTag: 7b6df0f3-46b3-4a1d-97a4-f18697ef1ce1
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column IDBarcoFecha = PB_VIAJE_MUESTREO_TEST[COD_BARCO]& "-" & YEAR(PB_VIAJE_MUESTREO_TEST[FECHA]) & MONTH(PB_VIAJE_MUESTREO_TEST[FECHA])
		lineageTag: ee737b2c-f438-417e-9ed4-a4f231ac9430
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column DuracionMarea = ABS(DATEDIFF(PB_VIAJE_MUESTREO_TEST[FECHA_HORA_ZARPE],PB_VIAJE_MUESTREO_TEST[FECHA_HORA_RECALADA],DAY))
		formatString: 0
		lineageTag: 026e3bd4-552d-4b26-90ff-67eeb2f320ee
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column PERIODOMES = ```
			FORMAT(PB_VIAJE_MUESTREO_TEST[FECHA], "YYYY-MM") 
			```
		lineageTag: 357edeaf-34fa-4442-9af9-b6d782e650c1
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column PROYECTO
		dataType: string
		lineageTag: cbf9317e-845f-4298-99f8-3934e277384e
		summarizeBy: none
		sourceColumn: PROYECTO

		annotation SummarizationSetBy = Automatic

	column CODIGO_PUERTO_BASE
		dataType: int64
		formatString: 0
		lineageTag: a0915edd-730d-4495-ad09-117952a66ea2
		summarizeBy: sum
		sourceColumn: CODIGO_PUERTO_BASE

		annotation SummarizationSetBy = Automatic

	column CODIGO_OBSERVADOR_CIENTIFICO
		dataType: int64
		formatString: 0
		lineageTag: 96f00e3d-5e15-4586-b3ae-16f556853591
		summarizeBy: none
		sourceColumn: CODIGO_OBSERVADOR_CIENTIFICO

		annotation SummarizationSetBy = Automatic

	column CODIGO_REGION
		dataType: int64
		formatString: 0
		lineageTag: d7b9adf0-60e9-4820-9e71-d2cac187f72d
		summarizeBy: none
		sourceColumn: CODIGO_REGION

		annotation SummarizationSetBy = Automatic

	column CODIGO_FLOTA
		dataType: int64
		formatString: 0
		lineageTag: 492e07fe-6236-4912-a7aa-cb3b3cb5f5dc
		summarizeBy: none
		sourceColumn: CODIGO_FLOTA

		annotation SummarizationSetBy = Automatic

	column LUGAR_MUESTREO
		dataType: string
		lineageTag: a4b7aa2e-1e38-477c-b32f-a55e68d682a6
		summarizeBy: none
		sourceColumn: LUGAR_MUESTREO

		annotation SummarizationSetBy = Automatic

	column COD_BARCO
		dataType: int64
		formatString: 0
		lineageTag: 656c3aa6-56ca-4186-9dac-6a025438c684
		summarizeBy: none
		sourceColumn: COD_BARCO

		annotation SummarizationSetBy = Automatic

	column FECHA_HORA_ZARPE
		dataType: dateTime
		formatString: General Date
		lineageTag: 21b7e37c-a93f-4aaa-9893-855759b51bce
		summarizeBy: none
		sourceColumn: FECHA_HORA_ZARPE

		variation Variación
			isDefault
			relationship: 350a5312-362a-467a-9548-1102eb6f64ab
			defaultHierarchy: LocalDateTable_bc0b6aec-16d3-4111-9bae-db6deb1a9845.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column FECHA_HORA_RECALADA
		dataType: dateTime
		formatString: General Date
		lineageTag: ec10deb4-32b9-4179-979e-64c74c208471
		summarizeBy: none
		sourceColumn: FECHA_HORA_RECALADA

		variation Variación
			isDefault
			relationship: c710ecf2-0aee-41c5-8a3f-ccfe0207c9c7
			defaultHierarchy: LocalDateTable_29a6f2b9-9c57-4c65-931d-1542e6accbc7.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column COD_ESPECIE_OBJETIVO
		dataType: int64
		formatString: 0
		lineageTag: 67c44fbb-fa3c-4317-b7d1-2480ff169505
		summarizeBy: sum
		sourceColumn: COD_ESPECIE_OBJETIVO

		annotation SummarizationSetBy = Automatic

	column CODIGO_PUERTO
		dataType: int64
		formatString: 0
		lineageTag: 38981090-5c71-4c2d-be7f-1e2cd987177b
		summarizeBy: none
		sourceColumn: CODIGO_PUERTO

		annotation SummarizationSetBy = Automatic

	column CODIGO_ZONA
		dataType: int64
		formatString: 0
		lineageTag: e830f7c3-5003-4faa-963b-3dfdde5b56c6
		summarizeBy: none
		sourceColumn: CODIGO_ZONA

		annotation SummarizationSetBy = Automatic

	column CODIGO_ACTIVIDAD
		dataType: int64
		formatString: 0
		lineageTag: b5ce9a89-4c0d-42fd-a8bf-a813f3df3f83
		summarizeBy: none
		sourceColumn: CODIGO_ACTIVIDAD

		annotation SummarizationSetBy = Automatic

	column COD_ESPECIE
		dataType: int64
		formatString: 0
		lineageTag: c7572233-e678-460d-bd2d-64cf2223b42f
		summarizeBy: none
		sourceColumn: COD_ESPECIE

		annotation SummarizationSetBy = Automatic

	column NRO_MUESTREOS_ESPECIE
		dataType: int64
		formatString: 0
		lineageTag: 41bb2e08-e2be-401f-939c-9814efdb791e
		summarizeBy: sum
		sourceColumn: NRO_MUESTREOS_ESPECIE

		annotation SummarizationSetBy = Automatic

	column NRO_EJEMPLARES
		dataType: int64
		formatString: 0
		lineageTag: de69d1c2-2d04-420f-95af-699ff8373571
		summarizeBy: sum
		sourceColumn: NRO_EJEMPLARES

		annotation SummarizationSetBy = Automatic

	column NRO_ESTRUCTURAS
		dataType: int64
		formatString: 0
		lineageTag: 103f07c5-5938-4575-9052-33f1fabd2cbc
		summarizeBy: sum
		sourceColumn: NRO_ESTRUCTURAS

		annotation SummarizationSetBy = Automatic

	column NRO_HOJAS
		dataType: int64
		formatString: 0
		lineageTag: 296730e3-6243-46af-a27b-7d7f0bf6200e
		summarizeBy: sum
		sourceColumn: NRO_HOJAS

		annotation SummarizationSetBy = Automatic

	column NRO_LANCES
		dataType: int64
		formatString: 0
		lineageTag: 624c1881-4a6e-42f7-b076-c00f92932b73
		summarizeBy: sum
		sourceColumn: NRO_LANCES

		annotation SummarizationSetBy = Automatic

	column FECHA
		dataType: dateTime
		formatString: Short Date
		lineageTag: 8ab54ae8-e05e-4cac-9567-a59e1a220514
		summarizeBy: none
		sourceColumn: FECHA

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column ProyectoFlotaRegionPeriodo = PB_VIAJE_MUESTREO_TEST[PROYECTO] & "-" & PB_VIAJE_MUESTREO_TEST[CODIGO_FLOTA]  & "-" & PB_VIAJE_MUESTREO_TEST[CODIGO_REGION] & "-" & PB_VIAJE_MUESTREO_TEST[PERIODOMES]
		lineageTag: f51e7f0f-2080-492b-a4e2-b184537ec3a0
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column NOMBRE_ESPECIE_SELECCIONADA = ```
			
			VAR cod =
			    IF (
			        PB_VIAJE_MUESTREO_TEST[CODIGO_ACTIVIDAD] = 40,
			        PB_VIAJE_MUESTREO_TEST[COD_ESPECIE_OBJETIVO],
			        PB_VIAJE_MUESTREO_TEST[COD_ESPECIE]
			    )
			VAR nombre =
			    LOOKUPVALUE (
			        'Dimension MAESTRO ESPECIE'[NOMBRE_ESPECIE],
			        'Dimension MAESTRO ESPECIE'[COD_ESPECIE], cod
			    )
			RETURN
			COALESCE ( nombre, "Sin nombre" )
			
			```
		lineageTag: d8c2729b-a2f3-4f22-bf42-3342b2538d22
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column AÑO
		dataType: int64
		formatString: 0
		lineageTag: 884f4ba1-9294-447a-9bc8-6bd0fdda598e
		summarizeBy: sum
		sourceColumn: AÑO

		annotation SummarizationSetBy = Automatic

	partition PB_VIAJE_MUESTREO_TEST = m
		mode: import
		source =
				let
				    Source = Sql.Databases("192.168.169.110"),
				    Analytics = Source{[Name="Analytics"]}[Data],
				    Fact_PB_VIAJE_MUESTREO = Analytics{[Schema="Fact",Item="PB_VIAJE_MUESTREO"]}[Data],
				    #"Added Custom" = Table.AddColumn(Fact_PB_VIAJE_MUESTREO, "FECHA", each DateTime.Date(DateTime.FromText([FECHA_HORA_RECALADA]))),
				    #"Changed Type" = Table.TransformColumnTypes(#"Added Custom",{{"FECHA", type date}}),
				    #"Valor reemplazado" = Table.ReplaceValue(#"Changed Type","DSA","DAP",Replacer.ReplaceText,{"PROYECTO"}),
				    #"Valor reemplazado1" = Table.ReplaceValue(#"Valor reemplazado","DCS","DAP",Replacer.ReplaceText,{"PROYECTO"}),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Valor reemplazado1",{{"FECHA_HORA_RECALADA", type datetime}, {"FECHA_HORA_ZARPE", type datetime}}),
				    #"Poner En Mayúsculas Cada Palabra" = Table.TransformColumns(#"Tipo cambiado",{{"LUGAR_MUESTREO", Text.Proper, type text}}),
				    #"Filas filtradas" = Table.SelectRows(#"Poner En Mayúsculas Cada Palabra", each ([FECHA] <> null and [FECHA] <> "")),
				    #"Agregar Año" = Table.AddColumn(#"Filas filtradas", "AÑO", each Date.Year([FECHA]), Int64.Type),
				
				    AnioActual = Date.Year(Date.From(DateTime.LocalNow())),
				    AnioMinimo = AnioActual - 5,
				
				    #"Filtrar últimos 5 años" = Table.SelectRows(#"Agregar Año", each [AÑO] >= AnioMinimo)
				
				in
				    #"Filtrar últimos 5 años"

	annotation PBI_ResultType = Exception

	annotation PBI_NavigationStepName = Navegación

