// Le damos la bienvenida a la vista de consultas DAX. Obtenga más información sobre las consultas DAX en https://aka.ms/dax-queries.
// Haga clic con el botón derecho en tablas, columnas o medidas en el panel de datos para acceder a consultas rápidas o pida ayuda a Copilot para escribir DAX.

// Seleccione "Ejecutar" para probar esta consulta DAX de ejemplo.
EVALUATE
 CALCULATETABLE(
        VALUES(REQ_VIAJE_MUESTREO[ID_FlotaRegionPeriodo]),
        USERELATIONSHIP(
            PB_VIAJE_MUESTREO[ID_FLOTAREGIONPERIODO],
            REQ_VIAJE_MUESTREO[ID_FLOTAREGIONPERIODO]
        )
    )


